# User config
author: "Grimheden Holdings Inc."
tagline: "Asset management"
description: "World leading asset management"
keywords: "Cash, money, income, investment"
email: "inquiries@grimhedenholdings.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"
spotify: "https://open.spotify.com/user/simongrimheden?si=iMm33LjuTBaHj7d3Az-fTw"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
