# User config
author: "Grimheden"
tagline: "Pengar"
description: "Investors letter"
keywords: "Cash, money, income, investment"
email: "contact@grimhedenholdings.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
